### ISSUE TITLE
Problem runing make_specs -v

### ISSUE THREAD

**Issue by JFMandujanoR** [ihmeuw/vivarium_uw_covid#13]
Hello,

I hope you are well. I am trying to make simulations but when I run "make_specs -v" I am getting this error:

Traceback (most recent call last):
  File "C:\Users\mandujanorey\AppData\Local\Continuum\anaconda3\envs\vivarium_uw_covid\Scripts\make_specs-script.py", line 33, in <module>
    sys.exit(load_entry_point('vivarium-uw-covid', 'console_scripts', 'make_specs')())
  File "C:\Users\mandujanorey\AppData\Local\Continuum\anaconda3\envs\vivarium_uw_covid\lib\site-packages\pkg_resources\__init__.py", line 488, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Users\mandujanorey\AppData\Local\Continuum\anaconda3\envs\vivarium_uw_covid\lib\site-packages\pkg_resources\__init__.py", line 2861, in load_entry_point
    return ep.load()
  File "C:\Users\mandujanorey\AppData\Local\Continuum\anaconda3\envs\vivarium_uw_covid\lib\site-packages\pkg_resources\__init__.py", line 2461, in load
    return self.resolve()
  File "C:\Users\mandujanorey\AppData\Local\Continuum\anaconda3\envs\vivarium_uw_covid\lib\site-packages\pkg_resources\__init__.py", line 2467, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\mandujanorey\vivarium_uw_covid\src\vivarium_uw_covid\__init__.py", line 7, in <module>
    from .data.loader import *
  File "c:\users\mandujanorey\vivarium_uw_covid\src\vivarium_uw_covid\data\loader.py", line 15, in <module>
    from vivarium_gbd_access import gbd
ModuleNotFoundError: No module named 'vivarium_gbd_access'

It seems that "vivarium_gbd_access.py" is missing. 

Also I found that the folder "artifacts" from "src/vivarium_uw_covid" is missing. I am doing something wrong while installing? I think I am using git-lsf

Thanks

**Comment by aflaxman** [comment]
Oh my, the instructions in the README are from a boilerplate that does not match well with the direction this project has gone so far!  Sorry for the misleading information, I will get them updated ASAP.

**Comment by aflaxman** [comment]
See if the updates in ff3dfe32005328c556fb2bb2c157b5d2cdf07917 make things work better for you
